name: site-deploy CI

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    
    - uses: actions/checkout@v3
    - name: Build app
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i
    - run: npm run build
    - name: Stop old instance
    - run: pm2 stop website
    - continue-on-error: true
    - name: Deploy new instance
    - run: pm2 start "npm run start" --name="website"
    - run: pm2 save