name: site-deploy CI

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Build and Deploy - Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install node modules    
      run: npm i
    - name: Build App  
      run: npm run build
    - name: Stop existing instance
      run: pm2 stop all
      continue-on-error: true
    - name: Start new instance  
      run: pm2 start "npm run start" --name="website"
    - name: Save PM2 State  
      run: pm2 save